name: Java CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        version: [ 8, 11, 17, 20 ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.version }}
          distribution: 'zulu'
          cache: 'maven'
      - name: Build with Maven
        run: mvn test
