name: Linux MUSL x64
on:
  - push
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'maven'
      - uses: uraimo/run-on-arch-action@v2
        with:
          arch: none
          distro: none
          base_image: amd64/alpine:latest
          shell: /bin/sh
          githubToken: ${{ github.token }}
          dockerRunArgs: |
            --volume "~/.m2:/root/.m2" --volume "${PWD}:/mnt"
          install: |
            apk add openjdk11-jdk git curl wget gzip
            wget https://raw.githubusercontent.com/jjlauer/provisioning/master/linux/bootstrap-maven.sh
            chmod +x ./bootstrap-maven.sh
            ./bootstrap-maven.sh
          run: |
            export PATH=$PATH:/opt/maven/current/bin
            cd /mnt
            mvn test